version: '3'
services:
  server:
    container_name: django-server
    image: django-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    ports:
      - 8000:8000
    restart: always
    command: ./wait-for-it.sh db:5432 -- python3 ./project/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    container_name: django-postgres
    image: postgres
    environment:
      - POSTGRES_DB=django_timezone
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
